# Generated by Django 3.2.12 on 2022-05-09 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('military_base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crewmember',
            old_name='name',
            new_name='lastName',
        ),
        migrations.AddField(
            model_name='crewmember',
            name='firstName',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crewmember',
            name='isOfficer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='code',
            field=models.CharField(max_length=200),
        ),
    ]
